# Generated by Django 5.1.4 on 2025-01-16 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(0)])),
                ('bssid', models.CharField(max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(0)])),
                ('security', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(0)])),
                ('mode', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(0)])),
            ],
        ),
    ]
